path: /home/featurize/datasets/visdrone
train: splits/visdrone/train_10pct.txt
val: VisDrone2019-DET-val/images
test: VisDrone2019-DET-test-dev/images
names:
  - pedestrian
  - people
  - bicycle
  - car
  - van
  - truck
  - tricycle
  - awning-tricycle
  - bus
  - motor
